"""
20.02.2023
More for Loops
Created by: Jessica Göckler
- Create a list that contains at least 20 different numbers that aren't sorted
  - Don't use range for the generation of the list
- Write a loop that runs ofer all elements of the list and adds them all up
  (sum up all elements)
- Write a second loop that tells the user for each element
  wheter is bigger, or lower than a number specified by him
  - this number should be generated by using input before the start of the loop
"""
list1 = [7, 36, 9, 15, 48, 46, 33, 14, 20, 38, 11, 19, 29, 42, 26, 49, 16, 50, 38, 1]
sum1 = 0

# print()
for elem1 in list1:
    sum1 += elem1
print("Sum of all numbers: \n",sum1)

input1 = int(input("What number do you want to compare with the numbers of the list? \n"))

for elem2 in list1:
    if input1 > elem2:
      print("Your number",input1,"is greater than",elem2)
    elif input1 < elem2:
      print("Your number",input1,"is smaller than",elem2)
    elif input1 == elem2:
      print("Your number",input1,"equals",elem2)
print("No comparisons left.")
