"""
22.02.2023
Created by: Jessica Göckler
Writing files
- Write a program that creates two different files
- The fist file should be opened normally, that means just use open() and no
  "with" and two lines should be written in it by using file.write()
- Afterwards close the file, open it again and add another three lines of the
  text to the file
- The second file should be generated by using "with" and a loop to write a
  countdown from 10 to 0
- Each number should be in a separate line, so you need to add "\n" to your
  file.write command
"""
file = open("Exercise_59_1.txt","w")
file.write("Good Morning! \n")
file.write("How are you? \n")
file.close()

file = open("Exercise_59_1.txt","a")
file.write("I am fine. \n")
file.write("Thank you! \n")
file.write("And how are you? \n")
file.close()

with open("Exercise_59_2.txt","w") as with_file:
    for i in range(10,-1,-1):
        with_file.write(str(i)+"\n")
